// URLICHT – Levels, Story und Ereignis-Abläufe.
// Ereignis: [Zeit in Sekunden, Typ, Parameter]

export const CAST = {
  juno: { name: 'Juno „Funke“ Varga', color: '#ffb347', pitch: 1.1, wave: 'square' },
  mira: { name: 'Mira „Parallaxe“ Oyelaran', color: '#ff9ad0', pitch: 1.35, wave: 'triangle' },
  brakk: { name: 'Brakk „Schrott“', color: '#b8c4d0', pitch: 0.55, wave: 'sawtooth' },
  pip: { name: 'Pip', color: '#fff6a0', pitch: 2.2, wave: 'sine' },
  tessaro: { name: 'Admiralin Tessaro', color: '#9fd8ff', pitch: 0.85, wave: 'square' },
  stille: { name: 'DIE STILLE', color: '#ffffff', pitch: 0.35, wave: 'sine' },
};

const L = (...ev) => ev;

export const PROLOG = [
  ['', 'Im Jahr 3127 bemerken Astronomen etwas Unmögliches.'],
  ['', 'Am Rand des beobachtbaren Universums verschwinden Galaxien. Nicht explodiert. Nicht verdunkelt. Einfach … fort.'],
  ['', 'Und die kosmische Hintergrundstrahlung – das älteste Licht, das es gibt – wird leiser.'],
  ['', 'Etwas kommt vom Rand her nach innen. Etwas, das kein Licht, keine Wärme und keine Masse hat.'],
  ['', 'Man nennt es: DIE STILLE.'],
];

export const LEVELS = [
  // =============================== 1 ===============================
  {
    id: 'ceres', name: 'Ceres-Werft', sub: 'Asteroidengürtel · Sol-System', music: 'ceres', medal: 90,
    env: { sky: '#05060f', fog: '#0a0c1a', fogNear: 150, fogFar: 330, stars: 1, backdrop: 'ceres', backdropPos: [150, 30], backdropSize: 320, speed: 60 },
    briefing: [
      ['tessaro', 'Hier spricht Admiralin Tessaro, Arche-Flotte. An alle Schiffe im Ceres-Sektor: Die Werft wird angegriffen!'],
      ['tessaro', 'Kurierschiff LUMEN, Sie sind am nächsten dran. Wer fliegt da?'],
      ['juno', 'Juno Varga, Kurierdienst. Ich soll den Prototyp eigentlich nur abliefern.'],
      ['tessaro', 'Neuer Auftrag, Varga: Halten Sie die Angreifer auf, bis die Flotte eintrifft.'],
      ['mira', 'Mira Oyelaran, Observatorium Ceres. Ich fliege mit dir, Juno. Diese Angreifer haben keine Signatur. Gar keine.'],
      ['brakk', 'Brakk. Ehemals Bergbauroboter, Modell BR-4K. Ich fliege auch mit. Irgendwer muss ja auf euch Fleischsäcke aufpassen.'],
      ['juno', 'Na dann. LUMEN – Start!'],
    ],
    checkpoint: 60,
    events: L(
      [0.5, 'tip', { text: 'Linke Bildschirmhälfte: STEUERN' }],
      [3, 'wave', { kind: 'drone', form: 'line', n: 5, y: 0 }],
      [5, 'tip', { text: 'Der Laser feuert automatisch.  FEUER halten = Ladeschuss, loslassen = zielsuchend!' }],
      [7, 'wave', { kind: 'drone', form: 'vee', n: 5 }],
      [9, 'decor', { kind: 'structure', n: 3 }],
      [10, 'decor', { kind: 'girder', x: -8, y: -2, len: 40 }],
      [11, 'say', { who: 'mira', text: 'Vorsicht, Werftträger! Nicht dagegenfliegen.' }],
      [13, 'wave', { kind: 'drone', form: 'swoopL', n: 5 }],
      [15, 'ring', { x: 0, y: 2 }],
      [16, 'wave', { kind: 'drone', form: 'swoopR', n: 5 }],
      [19, 'asteroids', { n: 10, min: 1.5, max: 3.5 }],
      [20, 'say', { who: 'brakk', text: 'Asteroiden. Meine alten Kollegen. Schieß ruhig, die sind nicht sehr gesprächig.' }],
      [23, 'wave', { kind: 'drone', form: 'hover', n: 3, y: 2, hoverT: 5 }],
      [24, 'tip', { text: 'ROLLE: Gegnerische Schüsse abprallen lassen!' }],
      [27, 'wave', { kind: 'dart', form: 'column', n: 4 }],
      [30, 'ring', { x: 6, y: 3, gold: true }],
      [32, 'wave', { kind: 'drone', form: 'sine', n: 6 }],
      [35, 'item', { kind: 'laser', x: 0, y: 0 }],
      [36, 'asteroids', { n: 14 }],
      [38, 'decor', { kind: 'girder', x: 0, y: 0, len: 30, vertical: true }],
      [40, 'wave', { kind: 'splitter', form: 'line', n: 1, y: 1 }],
      [41, 'say', { who: 'mira', text: 'Ein großer! Er teilt sich, wenn du ihn triffst!' }],
      [44, 'wave', { kind: 'drone', form: 'vee', n: 5 }],
      [46, 'chase', { who: 'brakk', text: 'Hey! Einer klebt an meinem Heck! Ich bin nicht mehr der Jüngste!' }],
      [50, 'wave', { kind: 'drone', form: 'swoopL', n: 6 }],
      [52, 'wave', { kind: 'drone', form: 'swoopR', n: 6 }],
      [55, 'ring', { x: -6, y: -2, gold: true }],
      [56, 'asteroids', { n: 12 }],
      [58, 'wave', { kind: 'drone', form: 'hover', n: 4, hoverT: 6 }],
      [62, 'decor', { kind: 'structure', n: 4 }],
      [63, 'wave', { kind: 'dart', form: 'vee', n: 5 }],
      [66, 'wave', { kind: 'drone', form: 'spiral', n: 6 }],
      [70, 'item', { kind: 'bomb', x: 4, y: 2 }],
      [71, 'tip', { text: 'BOMBE: räumt vor dir alles frei' }],
      [72, 'asteroids', { n: 16 }],
      [76, 'wave', { kind: 'splitter', form: 'line', n: 2 }],
      [80, 'wave', { kind: 'drone', form: 'line', n: 7 }],
      [83, 'ring', { x: 0, y: 4, gold: true }],
      [85, 'wave', { kind: 'drone', form: 'sine', n: 8 }],
      [88, 'say', { who: 'mira', text: 'Da vorn! Ein riesiges Signal … nein. Ein riesiges NICHTS!' }],
      [91, 'warn', { text: 'WARNUNG: GROSSES ECHO' }],
      [94, 'boss', { id: 'queen' }],
    ),
    outro: [
      ['mira', 'Juno … die Trümmer. Sie zerfallen nicht. Sie hören einfach auf zu existieren.'],
      ['mira', 'Das sind keine Maschinen. Das ist Vakuum. Leerer Raum in perfekter Ordnung.'],
      ['brakk', 'Ich hab schon Asteroiden gesprengt, die mehr Persönlichkeit hatten.'],
      ['tessaro', 'Gute Arbeit, LUMEN. Aber wir haben ein größeres Problem. Das Tiefenohr auf Tethys meldet Angriffe.'],
      ['mira', 'Das Tiefenohr! Das größte Radioteleskop im Sonnensystem. Es lauscht der kosmischen Hintergrundstrahlung – dem ältesten Licht des Universums.'],
      ['mira', 'Und seit drei Wochen wird dieses Licht … leiser.'],
      ['juno', 'Licht kann leiser werden?'],
      ['mira', 'Eigentlich nicht. Kurs auf Saturn. Tethys ist einer seiner Monde.'],
    ],
  },
  // =============================== 2 ===============================
  {
    id: 'tethys', name: 'Eismond Tethys', sub: 'Saturn-System', music: 'tethys', medal: 95,
    env: { sky: '#0a1024', fog: '#1a2a4a', fogNear: 100, fogFar: 280, stars: 0.8, ground: '#e0f4ff', groundY: -8, backdrop: 'saturn', backdropPos: [-140, 110], backdropSize: 420, speed: 62, light: '#d0e8ff' },
    briefing: [
      ['mira', 'Tethys. Ein Eismond mit gut tausend Kilometern Durchmesser. Unter dem Eis: das Tiefenohr.'],
      ['tessaro', 'Die Echos wollen die Antenne zerstören. Sichern Sie die Daten, bevor es zu spät ist.'],
      ['brakk', 'Tiefflug über Eis. Wenn ich einen Magen hätte, wäre mir jetzt schlecht.'],
      ['juno', 'Bleib dicht bei mir, Brakk. Wir fliegen durch die Eisbögen – das ist gut für die Aerodynamik.'],
      ['brakk', 'Das stimmt nicht.'],
      ['juno', 'Nein. Aber es macht Spaß.'],
    ],
    checkpoint: 60,
    events: L(
      [1, 'tip', { text: 'Durch die Eisbögen fliegen gibt Bonuspunkte!' }],
      [2, 'decor', { kind: 'pillar', n: 3 }],
      [4, 'wave', { kind: 'drone', form: 'line', n: 5, y: -3 }],
      [6, 'decor', { kind: 'arch', x: 0 }],
      [8, 'decor', { kind: 'pillar', n: 4 }],
      [9, 'turrets', { n: 2 }],
      [12, 'wave', { kind: 'drone', form: 'swoopL', n: 5, y: -2 }],
      [14, 'decor', { kind: 'arch', x: -4 }],
      [14.2, 'ring', { x: -4, y: -1 }],
      [16, 'turrets', { n: 3 }],
      [18, 'decor', { kind: 'pillar', n: 5 }],
      [20, 'wave', { kind: 'dart', form: 'vee', n: 5, y: 0 }],
      [22, 'say', { who: 'mira', text: 'Die Türme da unten schießen. Tief fliegen ist gefährlich – aber lohnend.' }],
      [24, 'decor', { kind: 'arch', x: 5 }],
      [24.2, 'ring', { x: 5, y: -1, gold: true }],
      [26, 'wave', { kind: 'drone', form: 'hover', n: 4, y: 0 }],
      [30, 'mines', { n: 6 }],
      [31, 'say', { who: 'brakk', text: 'Minen. Wer baut Minen aus Nichts? Das ist Verschwendung von Nichts.' }],
      [34, 'decor', { kind: 'pillar', n: 6 }],
      [36, 'item', { kind: 'laser', x: 0, y: -1 }],
      [38, 'wave', { kind: 'drone', form: 'sine', n: 6, y: -1 }],
      [40, 'turrets', { n: 3 }],
      [42, 'decor', { kind: 'arch', x: -5 }], [44, 'decor', { kind: 'arch', x: 0 }], [46, 'decor', { kind: 'arch', x: 5 }], [48, 'decor', { kind: 'arch', x: 0 }],
      [44.2, 'ring', { x: 0, y: -1 }], [48.2, 'ring', { x: 0, y: -1 }],
      [50, 'chase', { who: 'mira', text: 'Juno! Einer ist hinter mir! Ich werde ihn nicht los!' }],
      [55, 'wave', { kind: 'splitter', form: 'line', n: 1, y: 0 }],
      [58, 'decor', { kind: 'pillar', n: 6 }],
      [62, 'wave', { kind: 'dart', form: 'column', n: 5, y: -2 }],
      [64, 'turrets', { n: 4 }],
      [66, 'ring', { x: -6, y: 2, gold: true }],
      [68, 'wave', { kind: 'drone', form: 'swoopR', n: 6, y: -1 }],
      [70, 'mines', { n: 8 }],
      [73, 'decor', { kind: 'arch', x: 0 }], [75, 'decor', { kind: 'arch', x: 0 }], [77, 'decor', { kind: 'arch', x: 0 }],
      [80, 'wave', { kind: 'drone', form: 'vee', n: 7, y: 0 }],
      [82, 'item', { kind: 'bomb', x: 0, y: -1 }],
      [84, 'decor', { kind: 'pillar', n: 6 }],
      [86, 'say', { who: 'mira', text: 'Ich lade die Daten der Antenne … 40 Prozent … da kommt was aus dem Eis!' }],
      [89, 'warn', { text: 'WARNUNG: TIEFENWÄCHTER' }],
      [92, 'boss', { id: 'waechter' }],
    ),
    outro: [
      ['mira', 'Daten gesichert! Ich analysiere … Juno, das ist unglaublich.'],
      ['mira', 'Die Hintergrundstrahlung hat ein Muster. Ganz schwach, versteckt im Rauschen. Wie ein … Ton.'],
      ['juno', 'Ein Ton? Von wo?'],
      ['mira', 'Von überall. Das Muster stammt aus der Zeit, als das Universum 380.000 Jahre alt war – als es zum ersten Mal durchsichtig wurde.'],
      ['mira', 'Und etwas empfängt diesen Ton ebenfalls. Im Aurin-Nebel. Einem Gebiet, in dem Sterne entstehen.'],
      ['brakk', 'Ein Nebel. Toll. Da sieht man wenigstens nichts.'],
    ],
  },
  // =============================== 3 ===============================
  {
    id: 'aurin', name: 'Aurin-Nebel', sub: 'Sternentstehungsgebiet', music: 'aurin', medal: 95,
    env: { sky: '#1a0820', fog: '#3a1040', fogNear: 60, fogFar: 230, stars: 0.3, speed: 58, light: '#ffc0e8' },
    briefing: [
      ['mira', 'Der Aurin-Nebel. Eine Wolke aus Gas und Staub, hundert Lichtjahre groß. Hier werden gerade Sterne geboren.'],
      ['mira', 'Im Nebel sind die Sensoren fast blind. Wir fliegen nach Gefühl.'],
      ['juno', 'Mein Lieblings-Navigationssystem.'],
      ['brakk', 'Meins ist Panik. Funktioniert auch.'],
      ['mira', 'Das Signal kommt von … einem einzelnen Photon? Das ergibt keinen Sinn.'],
    ],
    checkpoint: 60,
    events: L(
      [0, 'decor', { kind: 'cloud', n: 6 }],
      [2, 'decor', { kind: 'protostar', color: '#ffb0e0', r: 6 }],
      [4, 'wave', { kind: 'drone', form: 'column', n: 5 }],
      [6, 'decor', { kind: 'cloud', n: 5 }],
      [8, 'mines', { n: 6 }],
      [10, 'wave', { kind: 'dart', form: 'vee', n: 5 }],
      [12, 'decor', { kind: 'cloud', n: 5 }],
      [13, 'decor', { kind: 'protostar', color: '#a0c0ff', r: 8 }],
      [14, 'say', { who: 'mira', text: 'Siehst du die leuchtenden Kugeln? Protosterne. Sternenbabys. In ein paar Millionen Jahren sind das Sonnen.' }],
      [16, 'wave', { kind: 'drone', form: 'spiral', n: 6 }],
      [18, 'decor', { kind: 'cloud', n: 5 }],
      [20, 'wave', { kind: 'drone', form: 'hover', n: 4 }],
      [22, 'ring', { x: 5, y: 3, gold: true }],
      [24, 'decor', { kind: 'cloud', n: 6 }],
      [24.5, 'wave', { kind: 'splitter', form: 'line', n: 1 }],
      [26, 'say', { who: 'pip', text: '… hallo? … Ist da jemand … der sieht?' }],
      [29, 'say', { who: 'juno', text: 'Wer war das?!' }],
      [31, 'say', { who: 'pip', text: 'Ich bin … alt. Sehr alt. Ich bin das erste Licht. Und ich werde gejagt.' }],
      [30, 'wave', { kind: 'dart', form: 'column', n: 6 }],
      [32, 'decor', { kind: 'cloud', n: 6 }],
      [34, 'mines', { n: 8 }],
      [35, 'item', { kind: 'laser', x: 0, y: 0 }],
      [38, 'wave', { kind: 'drone', form: 'sine', n: 7 }],
      [40, 'decor', { kind: 'cloud', n: 6 }],
      [42, 'chase', { who: 'brakk', text: 'Du da, Photon! Wenn du Licht bist, leuchte mal hinter mich! Da hängt einer dran!' }],
      [46, 'wave', { kind: 'drone', form: 'swoopL', n: 5 }],
      [48, 'wave', { kind: 'drone', form: 'swoopR', n: 5 }],
      [50, 'decor', { kind: 'cloud', n: 6 }],
      [50.5, 'decor', { kind: 'protostar', color: '#ffe0a0', r: 10 }],
      [52, 'say', { who: 'pip', text: 'Ich komme zu euch. Öffnet … die Luke. Ich bin ganz klein.' }],
      [55, 'say', { who: 'juno', text: 'Er ist … in meinem Cockpit. Ein leuchtender Punkt. Er summt.' }],
      [58, 'say', { who: 'pip', text: 'Danke. Ich nenne dich Funke. Du leuchtest ein bisschen.' }],
      [58.5, 'wave', { kind: 'splitter', form: 'vee', n: 3 }],
      [62, 'decor', { kind: 'cloud', n: 6 }],
      [64, 'wave', { kind: 'drone', form: 'hover', n: 5 }],
      [68, 'mines', { n: 10 }],
      [70, 'ring', { x: 0, y: 0, gold: true }],
      [72, 'wave', { kind: 'dart', form: 'vee', n: 7 }],
      [76, 'decor', { kind: 'cloud', n: 6 }],
      [78, 'wave', { kind: 'drone', form: 'spiral', n: 8 }],
      [82, 'item', { kind: 'bomb', x: 0, y: 0 }],
      [84, 'say', { who: 'pip', text: 'Er kommt. Der Wurm, der Licht frisst. Er folgt mir, seit die Sterne jung waren.' }],
      [87, 'warn', { text: 'WARNUNG: NEBELWURM' }],
      [90, 'boss', { id: 'wurm' }],
    ),
    outro: [
      ['pip', 'Er ist fort. Danke, Funke.'],
      ['mira', 'Pip … was genau bist du?'],
      ['pip', 'Ein Photon. Ich bin aufgebrochen, als das Universum 380.000 Jahre alt war. Seitdem fliege ich. 13,8 Milliarden Jahre lang.'],
      ['pip', 'Unterwegs habe ich zugehört. Und irgendwann … habe ich angefangen zu denken.'],
      ['juno', 'Und die Stille? Die Echos?'],
      ['pip', 'Die Stille war vor allem. Vollkommen. Glatt. Symmetrisch. Nichts war anders als irgendetwas anderes.'],
      ['pip', 'Dann – ein Ton. Die Symmetrie brach. Und aus dem Bruch wurde alles: Licht, Sterne, Planeten. Ihr.'],
      ['mira', 'Symmetriebrechung … Die Physik sagt tatsächlich: Kurz nach dem Anfang gab es ein winziges bisschen mehr Materie als Antimaterie. Eins zu einer Milliarde. Aus diesem Rest besteht alles.'],
      ['pip', 'Die Stille will ihre Vollkommenheit zurück. Sie kommt vom Rand. Und sie frisst das Universum von außen nach innen.'],
      ['brakk', 'Und wie hält man das Nichts auf?'],
      ['pip', 'Man fliegt zum Rand. Ich kenne den Weg. Ich BIN der Weg – der älteste Lichtstrahl. Folgt mir.'],
    ],
  },
  // =============================== 4 ===============================
  {
    id: 'licht', name: 'Das Letzte Licht', sub: 'Auf dem ältesten Lichtstrahl', music: 'licht', medal: 110,
    env: { sky: '#020208', fog: '#050510', fogNear: 160, fogFar: 380, stars: 1, backdrop: 'galaxy', backdropPos: [110, 40], backdropSize: 300, speed: 70, starColor: '#dde6ff' },
    briefing: [
      ['pip', 'Wir reiten auf meinem Weg zurück. Durch Raum und Zeit. Haltet euch fest.'],
      ['mira', 'Das beobachtbare Universum hat einen Durchmesser von etwa 93 Milliarden Lichtjahren. Wir fliegen gerade durch … alles.'],
      ['brakk', 'Und ich dachte, der Asteroidengürtel wäre groß.'],
      ['tessaro', 'LUMEN, wir verlieren Ihr Signal. Was immer Sie tun – viel Glück.'],
      ['juno', 'Keine Sorge, Admiralin. Wir bringen das Licht zurück.'],
    ],
    checkpoint: 60,
    events: L(
      [2, 'decor', { kind: 'wire', n: 2 }],
      [3, 'wave', { kind: 'drone', form: 'line', n: 6 }],
      [6, 'wave', { kind: 'dart', form: 'vee', n: 5 }],
      [8, 'decor', { kind: 'wire', n: 2 }],
      [10, 'env', { stars: 0.7, dur: 6 }],
      [11, 'say', { who: 'mira', text: 'Die Sterne … sie verschwinden. Einer nach dem anderen.' }],
      [12, 'wave', { kind: 'splitter', form: 'line', n: 2 }],
      [15, 'wave', { kind: 'drone', form: 'spiral', n: 8 }],
      [18, 'mines', { n: 8 }],
      [20, 'decor', { kind: 'wire', n: 3 }],
      [22, 'ring', { x: -5, y: 2, gold: true }],
      [23, 'wave', { kind: 'drone', form: 'hover', n: 5 }],
      [26, 'wave', { kind: 'dart', form: 'column', n: 6 }],
      [28, 'env', { stars: 0.45, backdropOpacity: 0.4, dur: 6 }],
      [29, 'say', { who: 'pip', text: 'Die Galaxie dort hinten … sie war einmal ein Lied mit hundert Milliarden Stimmen.' }],
      [32, 'wave', { kind: 'drone', form: 'sine', n: 8 }],
      [34, 'item', { kind: 'laser', x: 0, y: 0 }],
      [36, 'wave', { kind: 'splitter', form: 'vee', n: 3 }],
      [40, 'decor', { kind: 'wire', n: 3 }],
      [42, 'chase', { who: 'mira', text: 'Juno! Die Echos werden schneller! Einer hängt an mir!' }],
      [46, 'wave', { kind: 'dart', form: 'vee', n: 7 }],
      [50, 'mines', { n: 10 }],
      [52, 'env', { stars: 0.25, backdropOpacity: 0.12, fog: '#0a0a14', dur: 6 }],
      [54, 'say', { who: 'brakk', text: 'Es wird so … still hier. Selbst meine Lüfter klingen leiser.' }],
      [56, 'wave', { kind: 'drone', form: 'spiral', n: 10 }],
      [62, 'wave', { kind: 'drone', form: 'hover', n: 6 }],
      [66, 'ring', { x: 5, y: -3, gold: true }],
      [68, 'wave', { kind: 'dart', form: 'column', n: 8 }],
      [70, 'wave', { kind: 'splitter', form: 'line', n: 3 }],
      [74, 'decor', { kind: 'wire', n: 4 }],
      [76, 'item', { kind: 'bomb', x: 0, y: 0 }],
      [78, 'wave', { kind: 'drone', form: 'sine', n: 10 }],
      [82, 'say', { who: 'pip', text: 'Hört ihr sie? Die Echos singen. Sie singen die Stille.' }],
      [85, 'warn', { text: 'WARNUNG: DER CHOR' }],
      [88, 'boss', { id: 'chor' }],
    ),
    outro: [
      ['juno', 'Brakk …'],
      ['mira', 'Sein Signal ist weg. Er … er hat uns den Weg freigemacht.'],
      ['pip', 'Nichts geht wirklich verloren, Funke. Nicht im Universum. Es ändert nur seine Form.'],
      ['juno', 'Dann soll es nicht umsonst gewesen sein. Pip – bring uns zum Rand.'],
      ['pip', 'Wir sind schon da. Seht nach vorn.'],
    ],
  },
  // =============================== 5 ===============================
  {
    id: 'urlicht', name: 'Urlicht', sub: 'Der Rand des beobachtbaren Universums', music: 'urlicht', medal: 70, noBrakk: true, fireMul: 0.9,
    env: { sky: '#c85420', fog: '#e07030', fogNear: 70, fogFar: 260, stars: 0, speed: 60, light: '#ffe0c0' },
    briefing: [
      ['mira', 'Das ist … die Oberfläche der letzten Streuung. Eine Wand aus glühendem Plasma, 3000 Grad heiß. Weiter kann niemand sehen.'],
      ['mira', 'Das ist der Rand des beobachtbaren Universums. Dahinter war alles undurchsichtig. Dahinter … fing alles an.'],
      ['pip', 'Hier bin ich geboren. Hier wurde ich zum ersten Mal frei.'],
      ['stille', 'ALLES KEHRT ZURÜCK.'],
      ['stille', 'IHR SEID EIN FEHLER IN MEINER ORDNUNG. EIN SCHÖNER FEHLER. ABER EIN FEHLER.'],
      ['juno', 'Dann sind wir eben ein Fehler. Aber wir sind DA.'],
    ],
    checkpoint: 40,
    events: L(
      [0, 'decor', { kind: 'cloud', n: 5, color: '#ffe0a0' }],
      [6, 'decor', { kind: 'cloud', n: 5, color: '#ff5a2a' }],
      [12, 'decor', { kind: 'cloud', n: 5, color: '#ffd080' }],
      [18, 'decor', { kind: 'cloud', n: 5, color: '#ff7a3a' }],
      [24, 'decor', { kind: 'cloud', n: 5, color: '#ffe0a0' }],
      [30, 'decor', { kind: 'cloud', n: 5, color: '#ff5a2a' }],
      [36, 'decor', { kind: 'cloud', n: 5, color: '#ffd080' }],
      [42, 'decor', { kind: 'cloud', n: 5, color: '#ff7a3a' }],
      [48, 'decor', { kind: 'cloud', n: 5, color: '#ffe0a0' }],
      [54, 'decor', { kind: 'cloud', n: 5, color: '#ff5a2a' }],
      [62, 'decor', { kind: 'cloud', n: 5, color: '#ffd080' }],
      [72, 'decor', { kind: 'cloud', n: 5, color: '#ff7a3a' }],
      [84, 'decor', { kind: 'cloud', n: 5, color: '#ffe0a0' }],
      [1, 'wave', { kind: 'drone', form: 'line', n: 7 }],
      [4, 'wave', { kind: 'dart', form: 'vee', n: 7 }],
      [7, 'wave', { kind: 'splitter', form: 'line', n: 2 }],
      [10, 'say', { who: 'stille', text: 'WARUM WEHRT IHR EUCH? IN DER STILLE GIBT ES KEINEN SCHMERZ.' }],
      [13, 'say', { who: 'juno', text: 'In der Stille gibt es auch keine Musik. Keinen Kaffee. Kein Morgen.' }],
      [12, 'wave', { kind: 'drone', form: 'spiral', n: 10 }],
      [15, 'mines', { n: 10 }],
      [18, 'ring', { x: 0, y: 0, gold: true }],
      [20, 'wave', { kind: 'drone', form: 'hover', n: 6 }],
      [24, 'wave', { kind: 'dart', form: 'column', n: 8 }],
      [26, 'item', { kind: 'laser', x: 0, y: 0 }],
      [28, 'say', { who: 'mira', text: 'Juno, ihre Struktur! Perfekt symmetrisch. Wie ein Kristall. Wie das Nichts vor dem Anfang.' }],
      [31, 'say', { who: 'pip', text: 'Symmetrie ist Stille. Ein Bruch ist ein Ton. So hat alles angefangen.' }],
      [32, 'wave', { kind: 'splitter', form: 'vee', n: 3 }],
      [36, 'wave', { kind: 'drone', form: 'sine', n: 10 }],
      [42, 'item', { kind: 'bomb', x: 0, y: 0 }],
      [44, 'wave', { kind: 'dart', form: 'vee', n: 7 }],
      [48, 'say', { who: 'stille', text: 'KOMMT. SEHT MICH AN.' }],
      [50, 'warn', { text: 'DIE STILLE' }],
      [51, 'tip', { text: 'Die Kapseln heilen sich gegenseitig. Zerstöre eine ganze SEITE, um die Symmetrie zu brechen!' }],
      [53, 'boss', { id: 'stille' }],
    ),
    outro: [
      ['stille', '…'],
      ['stille', 'WARUM … KLINGT ES … SCHÖN?'],
      ['pip', 'Weil ein Bruch kein Fehler ist. Er ist ein Anfang.'],
      ['pip', 'Funke. Die Stille ist nicht fort. Sie wird immer am Rand warten. Jemand muss ihr antworten.'],
      ['juno', 'Pip … was hast du vor?'],
      ['pip', 'Ich bin das erste Licht. Ich gehe durch die Wand. Auf der anderen Seite ist die Stille vollkommen – noch.'],
      ['pip', 'Ich werde dort sein, was damals für euch der Ton war. Ein Bruch. Ein Anfang.'],
      ['mira', 'Du willst … ein neues Universum beginnen?'],
      ['pip', 'Kein Knall. Ein Lied. Es hat immer so angefangen.'],
      ['brakk', 'Ich hasse Abschiede. Meine Lüfter werden ganz feucht.'],
      ['juno', 'Werden wir dich wiedersehen?'],
      ['pip', 'Schaut nach oben. In 13,8 Milliarden Jahren wird irgendwo jemand in einem kleinen Schiff sitzen und sich fragen, woher das Licht kommt.'],
      ['pip', 'Grüßt ihn von mir.'],
    ],
  },
];

export const EPILOG = [
  ['', 'Pip flog in die Wand aus Licht. Für einen Augenblick wurde alles vollkommen hell.'],
  ['', 'Dann begann auf der anderen Seite etwas Neues.'],
  ['', 'Am Rand des Universums leuchten die Galaxien wieder. Die Hintergrundstrahlung ist lauter als je zuvor.'],
  ['', 'Wer genau hinhört, erkennt darin eine Melodie.'],
  ['', 'Das Universum ist kein Ort. Es ist ein Lied.'],
  ['', 'Und wir sind die Stellen, an denen es sich selbst zuhört.'],
];
