// URLICHT – Staffel NOVA: Figuren, Story und Level-Abläufe.
// Ereignis: [Zeit in Sekunden, Typ, Parameter]

export const CAST = {
  kira: { name: 'Kira Luchs', color: '#6ad8ff', pitch: 1.1, wave: 'square' },
  rasko: { name: 'Rasko Rabe', color: '#ff7a6a', pitch: 0.9, wave: 'sawtooth' },
  oli: { name: 'Oli Otter', color: '#9affb0', pitch: 1.6, wave: 'triangle' },
  hilde: { name: 'Hilde Dachs', color: '#ffd27a', pitch: 0.7, wave: 'square' },
  ursa: { name: 'Generalin Ursa', color: '#c8b0ff', pitch: 0.6, wave: 'triangle' },
  nihil: { name: 'Graf Zeno Nihil', color: '#c07aff', pitch: 0.8, wave: 'sawtooth' },
  vex: { name: 'Vex (Schakal-Staffel)', color: '#ff8ad0', pitch: 1.0, wave: 'sawtooth' },
  urlicht: { name: 'DAS URLICHT', color: '#fff2c0', pitch: 0.45, wave: 'sine' },
};

const L = (...ev) => ev;

export const PROLOG = [
  ['', 'Das Lyra-System. Sieben Welten, eine Sonne – und hinter allem, am Rand des sichtbaren Universums, ein uraltes Leuchten.'],
  ['', 'Man nennt es das Urlicht: das erste Licht, das je frei durch den Raum flog. Es ist 13,8 Milliarden Jahre alt. Und es glüht noch immer.'],
  ['', 'Vor zehn Jahren flog der Forscher Graf Zeno Nihil zum Rand, um es zu messen. Er kam verändert zurück – und verschwand.'],
  ['', 'Heute ist er wieder da. Mit einer Armee aus Stahl und Nullkristallen, die jedes Licht verschlucken.'],
  ['', 'Die Flotte von Aurelia ist geschlagen. Es bleibt eine letzte Hoffnung: die Söldnerstaffel NOVA.'],
];

export const LEVELS = [
  // =============================== 1 ===============================
  {
    id: 'aurelia', name: 'Aurelia', sub: 'Küste und Hafenstadt Portis', music: 'aurelia', medal: 80, boss: 'krabbe',
    env: {
      type: 'planet', speed: 58,
      sky: { top: '#2f6fd0', horizon: '#c4e2f4', bottom: '#8ab8d8', sunDir: [-0.45, 0.32, -1], sunColor: '#fff0c8' },
      fog: '#c0dcee', fogNear: 220, fogFar: 640, fluid: 'water',
      mountains: { color: '#7c98b4', height: 75, seed: 2 }, clouds: { n: 22 },
      light: '#d8ecff', groundLight: '#6a7a5a', sunLight: '#fff4e0', sunIntensity: 2.8,
    },
    sections: [[0, 'ocean'], [1650, 'city'], [4700, 'ocean']],
    briefing: [
      ['ursa', 'Staffel NOVA, hier spricht Generalin Ursa. Nihils Legion greift Portis an – unsere Hauptstadt.'],
      ['ursa', 'Unsere Flotte ist zerschlagen. Ihr seid alles, was wir noch haben.'],
      ['kira', 'Verstanden, Generalin. NOVA – in Formation!'],
      ['rasko', 'Formation? Ich dachte, wir improvisieren wieder. Darin sind wir Weltklasse.'],
      ['oli', 'Alle Systeme grün! Na ja, fast alle. Ein Lämpchen blinkt. Aber das blinkt immer.'],
      ['hilde', 'Kira, Kind. Denk dran: Wenn dir einer im Nacken sitzt – mach eine Rolle!'],
      ['kira', 'Hilde, ich fliege seit zwölf Jahren.'],
      ['hilde', 'Und seit zwölf Jahren vergisst du die Rolle.'],
    ],
    checkpoint: 50,
    events: L(
      [0.5, 'tip', { text: 'Linke Bildschirmhälfte: Finger ziehen = STEUERN' }],
      [3, 'wave', { kind: 'drone', form: 'line', n: 3, y: 9 }],
      [5, 'tip', { text: 'FEUER tippen = Laser  ·  FEUER halten = Zielschuss' }],
      [7, 'wave', { kind: 'drone', form: 'vee', n: 3, y: 10 }],
      [10, 'say', { who: 'rasko', text: 'Stachler der Legion! Zwei für mich, einer für dich, Chefin.' }],
      [11, 'wave', { kind: 'drone', form: 'swoopL', n: 4, y: 8 }],
      [13, 'tip', { text: 'BOOST / BREMSE: Tempo  ·  BOOST + Stick nach unten = LOOPING' }],
      [15, 'ring', { x: 0, y: 8 }],
      [17, 'wave', { kind: 'dart', form: 'column', n: 3, y: 7 }],
      [20, 'tip', { text: 'ROLLE: Feindliche Schüsse abprallen lassen' }],
      [21, 'wave', { kind: 'drone', form: 'hover', n: 3, y: 12 }],
      [25, 'say', { who: 'oli', text: 'Da vorne ist die Küste! Portis! Die Stadt brennt an drei Ecken!' }],
      [27, 'wave', { kind: 'drone', form: 'swoopR', n: 4, y: 12 }],
      [30, 'ring', { x: 0, y: 10, gold: true }],
      [32, 'tip', { text: 'Flieg durch die Tore für Bonuspunkte – und pass auf die Hochhäuser auf!' }],
      [33, 'tanks', { n: 2 }],
      [36, 'wave', { kind: 'drone', form: 'line', n: 4, y: 14 }],
      [38, 'say', { who: 'hilde', text: 'Panzer auf der Hauptstraße! Tief fliegen, Kira – aber nicht zu tief!' }],
      [40, 'item', { kind: 'laser', x: 0, y: 9 }],
      [42, 'wave', { kind: 'drone', form: 'dive', n: 3, y: 6 }],
      [45, 'chase', { who: 'rasko', text: 'Hey! Einer klebt an meinem Heck! Kira, schieß ihn runter – aber triff nicht MICH!' }],
      [49, 'tanks', { n: 2 }],
      [52, 'wave', { kind: 'splitter', form: 'line', n: 1, y: 14 }],
      [53, 'say', { who: 'oli', text: 'Ein Träger! Wenn der platzt, kommen Jäger raus. Wie bei einer Piñata. Einer bösen Piñata.' }],
      [57, 'ring', { x: 6, y: 12, gold: true }],
      [58, 'wave', { kind: 'drone', form: 'sine', n: 4, y: 12 }],
      [62, 'turrets', { n: 2 }],
      [64, 'wave', { kind: 'dart', form: 'vee', n: 3, y: 10 }],
      [67, 'item', { kind: 'bomb', x: -4, y: 10 }],
      [68, 'tip', { text: 'BOMBE: räumt vor dir alles frei' }],
      [70, 'wave', { kind: 'drone', form: 'swoopL', n: 4, y: 10 }],
      [74, 'tanks', { n: 3 }],
      [76, 'wave', { kind: 'drone', form: 'vee', n: 5, y: 12 }],
      [79, 'ring', { x: -6, y: 9, gold: true }],
      [81, 'say', { who: 'ursa', text: 'NOVA, im Hafen! Etwas Riesiges steigt aus dem Wasser!' }],
      [84, 'wave', { kind: 'drone', form: 'line', n: 3, y: 10 }],
      [87, 'warn', { text: 'WARNUNG: KRABBENLÄUFER' }],
      [90, 'boss', { id: 'krabbe' }],
    ),
    outro: [
      ['ursa', 'Portis ist frei! NOVA, die ganze Stadt jubelt. Ich höre es bis in den Bunker.'],
      ['oli', 'Ich hab mir die Wracks angesehen. Die Legion fliegt mit Nullkristallen. Die schlucken Licht wie ein Schwamm Wasser.'],
      ['oli', 'Und sie kommen alle aus dem Trümmergürtel.'],
      ['nihil', 'Wie rührend. Ein Luchs, ein Rabe, ein Otter und ein alter Dachs.'],
      ['nihil', 'Wisst ihr, was ihr seid? Unordnung. Flecken auf einem Bild, das perfekt sein könnte. Und ich räume auf.'],
      ['kira', 'Graf Nihil, nehme ich an. Dann räum dich schon mal warm.'],
      ['hilde', '… Zeno.'],
      ['rasko', 'Moment. Hilde, du KENNST den?'],
      ['hilde', 'Später, Junge. Erst der Trümmergürtel.'],
    ],
  },
  // =============================== 2 ===============================
  {
    id: 'truemmer', name: 'Trümmergürtel', sub: 'Nullkristall-Minen der Legion', music: 'truemmer', medal: 85, boss: 'felsbrecher',
    env: {
      type: 'space', speed: 60, base: '#04050c', nebula: ['#2a3a8a', '#6a2a7a', '#1a6a8a'], dust: 0.7,
      envMap: { top: '#c0d0f0', mid: '#4a5a8a', accent: '#7a4ab0', accent2: '#2a7ab0' },
      planet: { kind: 'saturn', size: 120, pos: [-330, 190, -780] },
      fog: '#0a0c1a', fogNear: 200, fogFar: 520, light: '#b8c8ff', groundLight: '#302040', hemi: 0.6, sunIntensity: 2.4,
    },
    briefing: [
      ['oli', 'Der Trümmergürtel. Hier ist vor Milliarden Jahren ein Planet zerbrochen. Jetzt baut Nihil hier Nullkristalle ab.'],
      ['rasko', 'Also: Steine ausweichen, Schiffe abschießen, Bergwerk kaputtmachen. Mein Lieblingsdreiklang.'],
      ['kira', 'Hilde. Du wolltest uns etwas erzählen.'],
      ['hilde', 'Nicht jetzt. Konzentriert euch. Da vorne ist ein Kreuzer, groß wie eine Stadt.'],
    ],
    checkpoint: 50,
    events: L(
      [2, 'asteroids', { n: 6 }],
      [4, 'wave', { kind: 'drone', form: 'line', n: 4, y: 0 }],
      [8, 'wave', { kind: 'drone', form: 'vee', n: 3, y: 3 }],
      [10, 'asteroids', { n: 6 }],
      [12, 'cruiser', { side: 1 }],
      [13, 'say', { who: 'oli', text: 'Kreuzer rechts! Die Geschütztürme auf dem Deck zuerst!' }],
      [16, 'wave', { kind: 'dart', form: 'column', n: 3, y: -2 }],
      [19, 'ring', { x: -4, y: 2 }],
      [20, 'wave', { kind: 'drone', form: 'swoopL', n: 4, y: 2 }],
      [23, 'asteroids', { n: 7, min: 2, max: 5 }],
      [25, 'item', { kind: 'laser', x: 0, y: 0 }],
      [27, 'wave', { kind: 'splitter', form: 'line', n: 1, y: 2 }],
      [30, 'mines', { n: 4 }],
      [31, 'say', { who: 'rasko', text: 'Minen! Wer lässt denn so was im All rumliegen? Unhöflich.' }],
      [33, 'wave', { kind: 'drone', form: 'hover', n: 3, y: 4 }],
      [36, 'cruiser', { side: -1 }],
      [38, 'ring', { x: 5, y: -3, gold: true }],
      [40, 'wave', { kind: 'drone', form: 'sine', n: 4, y: 0 }],
      [43, 'say', { who: 'hilde', text: 'Also gut. Vor zehn Jahren war ich Zenos Pilotin. Ich habe ihn zum Rand des Universums geflogen.' }],
      [48, 'say', { who: 'hilde', text: 'Er hat ins Urlicht geschaut. Stundenlang. Und als er zurückkam, hat er nie wieder gelacht.' }],
      [50, 'asteroids', { n: 8 }],
      [52, 'chase', { who: 'oli', text: 'Kiraaa! Da hängt einer hinter mir! Der ist schneller als ich! Alle sind schneller als ich!' }],
      [56, 'wave', { kind: 'dart', form: 'vee', n: 4, y: 1 }],
      [60, 'wave', { kind: 'splitter', form: 'line', n: 2, y: 0 }],
      [63, 'ring', { x: 0, y: 4, gold: true }],
      [64, 'mines', { n: 5 }],
      [67, 'wave', { kind: 'drone', form: 'swoopR', n: 5, y: -1 }],
      [70, 'item', { kind: 'bomb', x: 0, y: 0 }],
      [72, 'cruiser', { side: 1 }],
      [74, 'asteroids', { n: 8, min: 2, max: 5 }],
      [77, 'wave', { kind: 'drone', form: 'line', n: 5, y: 2 }],
      [80, 'say', { who: 'oli', text: 'Da ist die Mine! Ein Bergbauschiff – und es hat BOHRER! Große Bohrer!' }],
      [83, 'warn', { text: 'WARNUNG: FELSBRECHER' }],
      [86, 'boss', { id: 'felsbrecher' }],
    ),
    outro: [
      ['oli', 'Die Mine ist hin. Keine Nullkristalle mehr aus diesem Gürtel.'],
      ['rasko', 'Und jetzt, Hilde. Ohne Ausreden.'],
      ['hilde', 'Das Urlicht ist nicht einfach Licht. Es ist das Echo vom Anfang. Wer lange genug hineinsieht, sieht, woher alles kommt.'],
      ['hilde', 'Zeno hat gesehen, dass alles aus einem einzigen Punkt entstanden ist. Und dass alles wieder vergehen wird.'],
      ['hilde', 'Das hat ihm solche Angst gemacht, dass er beschlossen hat: Wenn alles vergeht, dann soll es wenigstens IHM gehören.'],
      ['kira', 'Er will das Urlicht besitzen?'],
      ['hilde', 'Er will es verschlucken. Mit einem Kern aus Nullkristallen. Und dann, sagt er, beginnt alles neu – nach seinen Regeln.'],
      ['oli', 'Die Kristalle werden auf Pyra verarbeitet. Dem Vulkanplaneten. Ich hab die Frachtrouten.'],
    ],
  },
  // =============================== 3 ===============================
  {
    id: 'pyra', name: 'Pyra', sub: 'Vulkanwelt · Schmiede der Legion', music: 'pyra', medal: 80, boss: 'magma',
    env: {
      type: 'planet', speed: 56,
      sky: { top: '#2a0c0a', horizon: '#d0582a', bottom: '#3a0e06', sunDir: [0.3, 0.2, -1], sunColor: '#ff9a50' },
      fog: '#7a2e14', fogNear: 140, fogFar: 520, fluid: 'lava', dust: 0.7, dustColor: '#ffa040',
      mountains: { color: '#2a1410', height: 90, seed: 5 }, clouds: { n: 14, color: '#4a2a26', opacity: 0.75 },
      light: '#ffb080', groundLight: '#ff5a1a', hemi: 0.8, sunLight: '#ffb070', sunIntensity: 2.2,
    },
    sections: [[0, 'lava'], [1300, 'canyon'], [2800, 'lava'], [3900, 'canyon'], [4600, 'lava']],
    briefing: [
      ['oli', 'Pyra. Oberflächentemperatur: ungemütlich. Die Lava ist 1200 Grad heiß.'],
      ['rasko', 'Also nicht reinfallen. Notiert.'],
      ['kira', 'Oli, empfängst du eigentlich immer noch dieses Rauschen?'],
      ['oli', 'Ja! Seit Aurelia. Es kommt aus allen Richtungen gleichzeitig. Das ist … die kosmische Hintergrundstrahlung. Das Urlicht.'],
      ['oli', 'Und es hat ein Muster. Fast wie eine Melodie.'],
    ],
    checkpoint: 45,
    events: L(
      [2, 'wave', { kind: 'drone', form: 'line', n: 3, y: 10 }],
      [5, 'say', { who: 'hilde', text: 'Nicht zu tief über der Lava! Das Schild hält das nicht lange aus.' }],
      [6, 'wave', { kind: 'drone', form: 'swoopR', n: 4, y: 12 }],
      [10, 'ring', { x: 0, y: 12 }],
      [12, 'wave', { kind: 'dart', form: 'column', n: 3, y: 9 }],
      [15, 'wave', { kind: 'drone', form: 'dive', n: 3, y: 8 }],
      [18, 'item', { kind: 'laser', x: 0, y: 12 }],
      [22, 'say', { who: 'rasko', text: 'Canyon voraus! Eng, heiß und voller Stachler. Also genau mein Humor.' }],
      [24, 'tanks', { n: 2 }],
      [26, 'wave', { kind: 'drone', form: 'hover', n: 3, y: 12 }],
      [30, 'turrets', { n: 2 }],
      [31, 'ring', { x: 4, y: 10, gold: true }],
      [33, 'wave', { kind: 'drone', form: 'sine', n: 4, y: 12 }],
      [37, 'chase', { who: 'hilde', text: 'Kind, ich hab einen am Schwanz! Und ich meine das wörtlich – er zielt auf meinen Schwanz!' }],
      [41, 'wave', { kind: 'splitter', form: 'line', n: 1, y: 13 }],
      [44, 'tanks', { n: 3 }],
      [47, 'wave', { kind: 'dart', form: 'vee', n: 3, y: 10 }],
      [50, 'say', { who: 'urlicht', text: '… … …' }],
      [53, 'say', { who: 'oli', text: 'Habt ihr das gehört?! Das Rauschen … es hat sich GEÄNDERT. Als würde jemand zuhören.' }],
      [55, 'wave', { kind: 'drone', form: 'swoopL', n: 4, y: 12 }],
      [58, 'ring', { x: -5, y: 14, gold: true }],
      [60, 'mines', { n: 4 }],
      [63, 'turrets', { n: 3 }],
      [66, 'wave', { kind: 'drone', form: 'vee', n: 5, y: 12 }],
      [69, 'item', { kind: 'bomb', x: 0, y: 12 }],
      [72, 'wave', { kind: 'splitter', form: 'line', n: 2, y: 14 }],
      [76, 'tanks', { n: 2 }],
      [79, 'say', { who: 'hilde', text: 'Die Lava bewegt sich. Da ist was drin. Was Langes.' }],
      [82, 'warn', { text: 'WARNUNG: MAGMASCHLANGE' }],
      [85, 'boss', { id: 'magma' }],
    ),
    outro: [
      ['oli', 'Die Schmiede ist aus. Und ich hab Nihils Baupläne!'],
      ['oli', 'Er baut am Rand einen Nullkern. So groß wie ein Mond. Der soll das Urlicht einsaugen.'],
      ['kira', 'Und was passiert dann?'],
      ['oli', 'Das Urlicht ist das erste Licht nach dem Anfang. Alles danach baut darauf auf. Wenn es verschwindet …'],
      ['hilde', '… dann verschwindet alles, was je daraus entstanden ist. Sterne. Planeten. Wir.'],
      ['rasko', 'Und übrig bleibt nur Nihil, in seiner Lieblingsfarbe. Toller Plan. Wirklich.'],
      ['oli', 'Seine letzte Relaisstation liegt auf Glacia. Wenn wir die ausschalten, kommen wir unbemerkt zum Rand.'],
    ],
  },
  // =============================== 4 ===============================
  {
    id: 'glacia', name: 'Glacia', sub: 'Eiswelt · Nihils Relaisstation', music: 'glacia', medal: 80, boss: 'schakale',
    env: {
      type: 'planet', speed: 60,
      sky: { top: '#2a5ab8', horizon: '#cfe2f6', bottom: '#a8c4e4', sunDir: [0.5, 0.25, -1], sunColor: '#ffffff' },
      fog: '#bcd2ea', fogNear: 220, fogFar: 580, fluid: 'ice', dust: 0.8, dustColor: '#ffffff',
      mountains: { color: '#a4bcd8', height: 100, seed: 9 }, clouds: { n: 18 },
      light: '#d8e8ff', groundLight: '#6a88b0', hemi: 0.6, sunIntensity: 2.2,
    },
    sections: [[0, 'ice'], [2400, 'hills'], [3000, 'ice']],
    briefing: [
      ['ursa', 'NOVA, hier Ursa. Auf Glacia sitzt Nihils Relaisstation. Schaltet sie aus, dann ist er blind.'],
      ['rasko', 'Eis. Ich hasse Eis. Meine Federn frieren.'],
      ['oli', 'Achtung, ich empfange fremde Jäger. Keine Legion … die fliegen viel zu gut.'],
      ['hilde', 'Oh nein. Die Schakal-Staffel. Söldner. Die fliegen für jeden, der zahlt.'],
    ],
    checkpoint: 45,
    events: L(
      [2, 'wave', { kind: 'drone', form: 'line', n: 3, y: 10 }],
      [5, 'wave', { kind: 'drone', form: 'swoopL', n: 4, y: 12 }],
      [8, 'ring', { x: 0, y: 10 }],
      [10, 'turrets', { n: 2 }],
      [12, 'wave', { kind: 'dart', form: 'column', n: 3, y: 12 }],
      [15, 'say', { who: 'vex', text: 'Na sieh mal an. Die berühmte Staffel NOVA. Ich bin Vex. Und ihr seid mein Zahltag.' }],
      [18, 'wave', { kind: 'drone', form: 'vee', n: 3, y: 12 }],
      [21, 'item', { kind: 'laser', x: 0, y: 12 }],
      [23, 'tanks', { n: 3 }],
      [26, 'wave', { kind: 'drone', form: 'hover', n: 3, y: 14 }],
      [30, 'ring', { x: -5, y: 12, gold: true }],
      [32, 'chase', { who: 'oli', text: 'Einer von Vex hängt an mir! Und der ist GUT! Kira, bitte, bitte, bitte!' }],
      [36, 'wave', { kind: 'dart', form: 'vee', n: 3, y: 10 }],
      [39, 'turrets', { n: 3 }],
      [42, 'wave', { kind: 'splitter', form: 'line', n: 1, y: 14 }],
      [45, 'say', { who: 'rasko', text: 'Grüne Hügel mitten im Eis? Die Station heizt den Boden. Wir sind nah dran!' }],
      [47, 'wave', { kind: 'drone', form: 'sine', n: 4, y: 12 }],
      [50, 'tanks', { n: 3 }],
      [53, 'ring', { x: 5, y: 13, gold: true }],
      [55, 'wave', { kind: 'drone', form: 'dive', n: 4, y: 8 }],
      [58, 'mines', { n: 4 }],
      [62, 'wave', { kind: 'dart', form: 'column', n: 4, y: 12 }],
      [65, 'item', { kind: 'bomb', x: 0, y: 12 }],
      [67, 'wave', { kind: 'drone', form: 'swoopR', n: 5, y: 12 }],
      [71, 'turrets', { n: 3 }],
      [74, 'say', { who: 'oli', text: 'Relaisstation ist unten! Nihil ist blind!' }],
      [76, 'say', { who: 'vex', text: 'Blind vielleicht. Aber wir sehen euch noch prima. Schakale – Angriff!' }],
      [79, 'warn', { text: 'WARNUNG: SCHAKAL-STAFFEL' }],
      [82, 'boss', { id: 'schakale' }],
    ),
    outro: [
      ['vex', 'Autsch. Na gut, Luchs. Du fliegst besser als ich dachte.'],
      ['kira', 'Warum arbeitest du für einen, der das Universum auslöschen will?'],
      ['vex', 'Er hat uns nicht mal bezahlt. Er sagt, Geld sei auch nur Unordnung. Ich hätte zuhören sollen.'],
      ['vex', 'Hier. Die Koordinaten seines Throns. Tu mir einen Gefallen, Luchs: Mach ihn richtig platt.'],
      ['ursa', 'NOVA, die Flotte hält das Lyra-System. Den Rest schafft nur ihr. Fliegt zum Rand.'],
      ['hilde', 'Ich kenne den Weg. Ich wollte ihn nie wieder fliegen.'],
      ['kira', 'Diesmal fliegst du ihn nicht allein.'],
    ],
  },
  // =============================== 5 ===============================
  {
    id: 'rand', name: 'Der Rand', sub: 'Am Urlicht · Grenze des sichtbaren Universums', music: 'rand', medal: 70, boss: 'nihil',
    env: {
      type: 'space', speed: 62, base: '#120604', nebula: ['#ff9a40', '#ff6a2a', '#c04a8a', '#ffc070'], nebulaDensity: 1.3, nebulaGlow: 0.9, skyStars: 0.4, dust: 0.5, dustColor: '#ffd8a0',
      envMap: { top: '#fff0d0', mid: '#ff9a4a', horizon: '#e06a2a', bottom: '#4a1a10', accent: '#ffe0a0', accent2: '#c04a8a' },
      fog: '#3a1408', fogNear: 200, fogFar: 520, light: '#ffe0c0', groundLight: '#4a1a30', hemi: 0.8, sunLight: '#ffe8c0', sunIntensity: 2.6,
      wall: true,
    },
    briefing: [
      ['oli', 'Da ist es. Das Urlicht. Eine Wand aus glühendem Plasma, 3000 Grad heiß – so sah das Universum aus, als es 380.000 Jahre alt war.'],
      ['oli', 'Weiter kann niemand sehen. Dahinter war alles so heiß und dicht, dass kein Licht entkam. Dahinter … fing alles an.'],
      ['hilde', 'Genauso sah es damals aus. Nur … ohne die Armee.'],
      ['nihil', 'Willkommen am Rand, Staffel NOVA. Seht es euch an. Jede Sonne, jedes Lachen, jede Katastrophe – alles folgt aus diesem einen Leuchten.'],
      ['nihil', 'Und ich werde es trinken. Dann beginnt alles von vorn. Diesmal ordentlich. Diesmal in MEINER Farbe.'],
      ['kira', 'Ein Chamäleon, das nur eine einzige Farbe will. Das ist fast schon traurig, Graf.'],
      ['hilde', 'Zeno. Hör auf. Du hattest damals Angst. Das ist keine Schande. Aber das hier ist Wahnsinn.'],
      ['nihil', 'Hilde. Du bist immer noch zu weich. Genau wie das ganze Universum.'],
    ],
    checkpoint: 40,
    events: L(
      [2, 'wave', { kind: 'drone', form: 'line', n: 4, y: 0 }],
      [5, 'wave', { kind: 'dart', form: 'vee', n: 3, y: 2 }],
      [8, 'cruiser', { side: -1 }],
      [10, 'asteroids', { n: 5 }],
      [12, 'wave', { kind: 'drone', form: 'swoopR', n: 4, y: 1 }],
      [15, 'ring', { x: 0, y: 0, gold: true }],
      [16, 'say', { who: 'urlicht', text: 'ICH … SEHE … EUCH.' }],
      [19, 'say', { who: 'oli', text: 'Leute. Das Urlicht. Es hat gerade GESPROCHEN.' }],
      [21, 'wave', { kind: 'splitter', form: 'line', n: 2, y: 0 }],
      [24, 'item', { kind: 'laser', x: 0, y: 0 }],
      [26, 'cruiser', { side: 1 }],
      [28, 'wave', { kind: 'drone', form: 'sine', n: 5, y: 2 }],
      [31, 'mines', { n: 5 }],
      [33, 'say', { who: 'urlicht', text: 'IHR SEID AUS MIR GEMACHT. ALLE. AUCH ER.' }],
      [36, 'wave', { kind: 'dart', form: 'column', n: 4, y: -2 }],
      [39, 'ring', { x: -5, y: 3, gold: true }],
      [40, 'wave', { kind: 'drone', form: 'hover', n: 4, y: 2 }],
      [43, 'item', { kind: 'bomb', x: 0, y: 0 }],
      [45, 'wave', { kind: 'drone', form: 'vee', n: 5, y: 0 }],
      [48, 'say', { who: 'rasko', text: 'Da ist der Thron! Und – ist das ein KOPF? Ein riesiger Chamäleonkopf?!' }],
      [50, 'warn', { text: 'GRAF NIHIL' }],
      [51, 'tip', { text: 'Zerstöre zuerst die Augen – dann ist das Maul verwundbar!' }],
      [53, 'boss', { id: 'nihil' }],
    ),
    outro: [
      ['nihil', 'Nein … mein Thron … er fällt ins Licht …'],
      ['hilde', 'ZENO!'],
      ['nihil', 'Es ist … so hell. Hilde. Warum tut es nicht weh?'],
      ['urlicht', 'WEIL ICH DICH NIE FRESSEN WOLLTE, ZENO. ICH HABE DICH GEMACHT. WIE ALLES.'],
      ['urlicht', 'DU HAST GESEHEN, DASS ALLES VERGEHT. ABER DU HAST NICHT HINGESEHEN, WIE ES ENTSTEHT.'],
      ['nihil', '… Es sind … so viele Farben.'],
      ['hilde', 'Leb wohl, Zeno. Diesmal hast du richtig hingesehen.'],
      ['urlicht', 'KOMMT NÄHER, KLEINE LICHTER. ICH ZEIGE EUCH, WOHER IHR KOMMT.'],
    ],
  },
];

export const EPILOG = [
  ['', 'Das Licht umhüllt die vier Schiffe. Und für einen Augenblick sehen sie alles.'],
  ['', 'Einen Punkt, heißer als alles, was je sein wird. Er dehnt sich aus. Raum entsteht. Zeit beginnt zu laufen.'],
  ['', 'Materie und Antimaterie löschen sich gegenseitig aus – fast vollständig. Auf eine Milliarde Paare bleibt ein einziges Teilchen übrig.'],
  ['', 'Aus diesem winzigen Rest wird alles: Wasserstoff, die ersten Sterne, Galaxien, Staub, Planeten.'],
  ['', 'Eine blaue Welt namens Aurelia. Ein Luchs, der zum ersten Mal in ein Cockpit steigt.'],
  ['oli', 'Wir sind … übrig gebliebenes Licht. Das ist das Schönste, was ich je gemessen habe.'],
  ['rasko', 'Ich sag\'s ungern, aber: Ich hab Gänsehaut. Unter den Federn.'],
  ['hilde', 'Er hatte Angst vor dem Ende. Dabei war der Anfang die ganze Zeit hier.'],
  ['kira', 'NOVA an Aurelia. Mission erfüllt. Wir kommen nach Hause.'],
  ['', 'Am Rand des Universums leuchtet ein Licht. Es ist das älteste Licht, das es gibt.'],
  ['', 'Und es freut sich jedes Mal, wenn jemand zurückschaut.'],
];
